server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: collector-service
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: user
    password: password
  lifecycle:
    timeout-per-shutdown-phase: 30s

external:
  events-url: http://161.97.101.10:9797/events
